### PR TITLE
Scalable Microgrid

### PR DESCRIPTION
**Pull request by reid-g**
Adds a scalable microgrid as an example. This grid can be scaled to be an arbitrary size.

### CODE REVIEW

**Review by pelesh — CHANGES_REQUESTED** [review]
History of this branch seems to be polluted by merging from different feature branches. There cannot possibly be changes to 70 files given the scope of this PR. There are multiple conflicts preventing merging this branch. The branch needs to be rebased to `develop`. This may be nontrivial, though.

**Comment by pelesh** [comment]
`DistributedGenerator` class has disappeared and is replaced by `DiscreteGenerator` class. The two do not have the same objects.

**Comment by reid-g** [comment]
This branch has too many issues with the rebasing. Opening a separate pull request with new branch created from `develop`. Closing this pull request.

**Comment by reid-g** [comment]
Reference #11 for fixed git history

**Pull request closed without merging**
