### PR TITLE
Github actions

### PR DESCRIPTION
**Pull request by nkoukpaizan**
Use GitHub actions to set up basic testing for GridKit: Run all GridKit examples on pull request.

### CODE REVIEW

**Comment by pelesh** [comment]
The last commit [7491446](https://github.com/ORNL/GridKit/pull/36/commits/7491446270843717cbce4832f655dc2a30462530) seemed to work fine. @nkoukpaizan did you rebase to latest `develop`? There was a bug getting false negatives to "scale microgrid" test, which was fixed in #30.

**Comment by nkoukpaizan** [comment]
Rebased, but that test is still failing in CI. I will investigate.

**Comment by pelesh** [comment]
@nkoukpaizan, I suggest commenting out failing test and ready this PR for the merge. The failing test is fixed in #37. I suggest merging this PR first.

**Review by pelesh — APPROVED** [review]
Good starting point for CI testing.

**Pull request merged**
